### ISSUE TITLE
Wrong comment for the fitness function in Knapsack example

### ISSUE THREAD

**Issue by discosultan** [Martin1887/oxigen#15]
Seems like a comment for the N Queen example instead.

https://github.com/Martin1887/oxigen/blob/c39aee22424f5cf803a9224a08c0051479cf424a/knapsack-oxigen/src/main.rs#L79-L81

**Comment by Martin1887** [comment]
Fixed.

Thanks for your contribution.

**Comment by discosultan** [comment]
Thank you.
