### ISSUE TITLE
one max bug

### ISSUE THREAD

**Issue by jianshu93** [Martin1887/oxigen#22]
Hello,

See below:

error[E0046]: not all trait items implemented, missing: `GenotypeHash`, `hash`
  --> onemax-oxigen/src/main.rs:19:1
   |
19 | impl Genotype<bool> for OneMax {
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ missing `GenotypeHash`, `hash` in implementation
   |
   = help: implement the missing item: `type GenotypeHash = Type;`
   = help: implement the missing item: `fn hash(&self) -> <Self as oxigen::Genotype<T>>::GenotypeHash { todo!() }`

error[E0046]: not all trait items implemented, missing: `GenotypeHash`, `hash`
  --> knapsack-oxigen/src/main.rs:52:1
   |
52 | impl<'a> Genotype<bool> for Knapsack<'a> {
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ missing `GenotypeHash`, `hash` in implementation
   |
   = help: implement the missing item: `type GenotypeHash = Type;`
   = help: implement the missing item: `fn hash(&self) -> <Self as oxigen::Genotype<T>>::GenotypeHash { todo!() }`

For more information about this error, try `rustc --explain E0046`.
error: could not compile `onemax-oxigen` due to previous error
warning: build failed, waiting for other jobs to finish...
warning: panic message is not a string literal
   --> fd-oxigen/src/main.rs:220:25
    |
220 |             _ => panic!(format!("Incorrect index passed to n_values: {}", index)),
    |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: `#[warn(non_fmt_panics)]` on by default
    = note: this usage of panic!() is deprecated; it will be a hard error in Rust 2021
    = note: for more information, see <https://doc.rust-lang.org/nightly/edition-guide/rust-2021/panic-macro-consistency.html>
    = note: the panic!() macro supports formatting, so there's no need for the format!() macro here
help: remove the `format!(..)` macro call
    |
220 -             _ => panic!(format!("Incorrect index passed to n_values: {}", index)),
220 +             _ => panic!("Incorrect index passed to n_values: {}", index),
    | 

warning: `fd-oxigen` (bin "fd-oxigen") generated 1 warning
error: build failed

Thanks,

Jianshu

**Comment by Martin1887** [comment]
Hello.

It is bug of cargo workspaces when some crates have features in dependencies and other have not. Compile only one project each time (entering in its folder) instead of all at once from the workspace folder and everything should work (see #12, #19 and the building section of the `README.md` [https://github.com/Martin1887/oxigen#building]).

Regards,
