### ISSUE TITLE
Spelling mistake

### ISSUE THREAD

**Issue by lovasoa** [Martin1887/oxigen#3]
The word 'cuadratic' doesn't exist in english. You probably meant 'quadratic'.

https://en.wikipedia.org/wiki/Quadratic_function

**Comment by Martin1887** [comment]
You are right, I will fix it soon.

Thanks.

**Comment by lovasoa** [comment]
You're welcome :)

**Comment by Martin1887** [comment]
Fix in #8 (2.0 version). I have not fixed in 1.x branch because I don't want to break the interface.
