### ISSUE TITLE
Introduce a GeneticExecutionBuilder

### ISSUE THREAD

**Issue by garro95** [Martin1887/oxigen#6]
I like the way a new GeneticExecution object is built.
According to the [Rust Guidelines](https://doc.rust-lang.org/1.0.0/style/ownership/builders.html), although, there should be another object, called `...Builder`, that provides such an API.
The builder methods could take &mut Builder and return the reference, thus being more flexible, while only the final method, that build the actual object, would take the ownership.
On the final type, methods that have the name of a field should be getters for that field instead.

**Comment by Martin1887** [comment]
Ok, it is always better following the guidelines, so this will be modified in 2.x.

**Comment by garro95** [comment]
I did this, but I don't like the current interface. It needs to be improved.

**Comment by Martin1887** [comment]
I have not found a clean interface using a builder, maybe a future major version of Oxigen will implement it.

**Comment by Martin1887** [comment]
I see the `Command` example of https://doc.rust-lang.org/1.0.0/style/ownership/builders.html similar to the `GeneticExecution` of Oxigen, so this issue can be closed.
