### ISSUE TITLE
Individuals from shorter iterators

### ISSUE THREAD

**Issue by garro95** [Martin1887/oxigen#7]
Why at a certain point the optimizer starts to generate individuals with a minor number of elements?
Is it intended behavior?
How can this effect be counteracted?
Thanks!

**Comment by Martin1887** [comment]
Do you mean that individuals start to have less genes than other individuals?

That should not happen, but I have not observed it. Could you provide an example of this behavior?


Thanks.

**Comment by garro95** [comment]
I found a workaround for this: give a very high penalty to incomplete individuals, so that they are not selected.

**Comment by Martin1887** [comment]
I understand that your `generate` function creates individuals of different length. In general is preferable that all individuals have the same number of genes, what is the problem that you are solving?, maybe a better codification for it exists.

Nevertheless, reviewing the code I have not found any part where shorter individuals could be benefited (although I have not tried a variable-sized population yet).

Knowing the problem that you are trying to solve and the manner in which you are solving it would help to understand better the issue and maybe debugging would let me to find the point in which shorter individuals are benefited.

Thanks!

**Comment by garro95** [comment]
I am not generating a variable sized population. All my individuals have the same size. I invited you to join a private repository where you can see my source code.

**Comment by Martin1887** [comment]
I have been waiting your response in your private repository from weeks because I cannot reproduce the issue without the input arguments.

I want to fix this issue before publishing the 2.0 version, but I will wait only another week.


Regards.

**Comment by Martin1887** [comment]
The problem was in the user's `fix` function, not in `oxigen`.
