### ISSUE TITLE
Support for a reference environment

### ISSUE THREAD

**Issue by oinoom** [Martin1887/oxigen#9]
**Is your feature request related to a problem? Please describe.**
I am attempting to optimize for a graph-related problem and would like to create a genotype whose `fitness` function is calculated based on some reference graph, which ideally would be part of some read-only environment. 
  
It seems that, internally in `oxigen/lib.rs`, fitness is calculated for individuals generated with `generate` (see [here](https://github.com/Martin1887/oxigen/blob/master/oxigen/src/lib.rs#L310)), which can only take in a `ProblemSize` instance passed via [`genotype_size()`](https://github.com/Martin1887/oxigen/blob/master/oxigen/src/lib.rs#L198). 
  
So, either it appears that any `fitness` method I define cannot refer to the graph I wish to optimize against because that is decided at runtime _**or**_ I must smuggle the graph in as part of the `ProblemSize` passed into the `genotype_size()` method. Is this the correct interpretation?

In effect, `ProblemSize` is acting as the environment type and field. For example, it appears this is the case in the knap-sack example where the `items` are constructed (see [here](https://github.com/Martin1887/oxigen/blob/master/knapsack-oxigen/src/main.rs#L191)) and passed in as part of the problem size.

**Describe the solution you'd like**
Rename 

1. `ProblemSize`
2. `genotype_size(mut self, new_size: Ind::ProblemSize)`, and 
3. `GeneticExecution.genotype_size` 

to 

1. `Environment`
2. `set_environment(mut self, env: Ind::Environment)`, and
3. `GeneticExecution.environment`, respectively

**Describe alternatives you've considered**
No alternatives considered.

**Additional context**
No additional context.

**Comment by Martin1887** [comment]
Hello.

Yes, you are right, in knapsack problem I used the `ProblemSize` to pass additional information, and this was the first time that I had to do it, when the interface was already defined.

Your change is good, `Environment` is a better name. However, this change breaks the current interface, so it cannot be merged in the current version. I have created a 3.0 branch where I have merged your pull request, but note that I will not release a 3.0 version until I do more changes, what unfortunately will not happen in the short time.

How has been your experience with Oxigen beyond this issue? I hope that you have enjoyed it. Anything that you would like to have in a future version? I have planned a metagenotype to automatically get the best parameters for your genetic algorithm, maybe something similar for coevolution, macros to minimize the boilerplate in genotypes of basic types, maybe Python bindings, improve statistics, maybe hall of fame, binary and Gray coding utilities, the other open issues and trying to improve even more the performance.

Thanks for your contribution!

**Comment by oinoom** [comment]
I'll be sure to let you know about any feedback -- I started using the library yesterday. This seems to be the most promising of all the Rust genetic algorithm libraries I could find, if that's worth anything. Thank you for checking out the issue and PR so quickly! I'm happy to contribute more as I continue trying out the library.
